/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package gitee.com/lovewonyoung/CanMix/tp_dll */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "exports.go"

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>

// Define the function pointer type for the Tx callback
// id: CAN ID
// data: pointer to data buffer
// len: length of data
typedef void (*TxCallback)(uint32_t id, uint8_t* data, int len);

// Helper function to call the callback from Go
static void call_tx_callback(TxCallback cb, uint32_t id, uint8_t* data, int len) {
    if (cb != NULL) {
        cb(id, data, len);
    }
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// GoInitTp initializes the ISO-TP layer.
// rxID: The CAN ID to listen for.
// txID: The CAN ID to transmit with.
// isFD: Whether to use CAN FD.
// cb: The callback function for transmitting CAN frames.
//
extern void GoInitTp(GoUint32 rxID, GoUint32 txID, GoUint8 isFD, TxCallback cb);

// GoInputCanFrame is called by the external application when a CAN frame is received.
// id: CAN ID
// data: pointer to data
// len: length of data
//
extern void GoInputCanFrame(GoUint32 id, uint8_t* data, GoInt length);

// GoSendTp sends data via ISO-TP.
// data: pointer to data
// length: length of data
//
extern void GoSendTp(uint8_t* data, GoInt length);

// GoRecvTp receives data from ISO-TP.
// buffer: pointer to buffer to write to
// capacity: size of buffer
// timeoutMs: timeout in milliseconds
// returns: number of bytes written, or 0 if timeout/empty, -1 if buffer too small
//
extern GoInt GoRecvTp(uint8_t* buffer, GoInt capacity, GoInt timeoutMs);
extern void GoCloseTp(void);

#ifdef __cplusplus
}
#endif
